# Generated by Django 4.1.1 on 2022-11-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0003_alter_urls_options_alter_region_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='url',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
