# Generated by Django 4.1.1 on 2022-11-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0004_urls_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=255)),
            ],
        ),
    ]
